// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Microsoft.Automata.Templates
{
    using System.Collections.Generic;
    using Microsoft.Automata;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\GitHub\Automata\src\Automata\Templates\AutomatonMovesTextTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class AutomatonMovesTextTemplate : AutomatonMovesTextTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            
            #line 5 "C:\GitHub\Automata\src\Automata\Templates\AutomatonMovesTextTemplate.tt"
  // This template generates valid C# or C++ depending on the isAtEndConditionText and readNextCharText parameters passed in

    var stack = new Stack<int>();
    var set = new HashSet<int>();
    stack.Push(automaton.InitialState);
    set.Add(automaton.InitialState);
        
    Predicate<int> isFinalSink = (q =>
        (automaton.GetMovesCountFrom(q) == 1 && automaton.IsLoopState(q)
        && automaton.IsFinalState(q) && automaton.GetMoveFrom(q).Label.IsFull));

    Predicate<int> isNonfinalSink = (q =>
        (!automaton.IsFinalState(q) &&
            (automaton.GetMovesCountFrom(q) == 0 ||
            (automaton.GetMovesCountFrom(q) == 1 && automaton.IsLoopState(q)))));

    while (stack.Count > 0)
    {
        int q = stack.Pop();
        bool qIsComplete = false;
        if (automaton.InDegree(q) > 0) {
            
            #line default
            #line hidden
            this.Write("            State");
            
            #line 26 "C:\GitHub\Automata\src\Automata\Templates\AutomatonMovesTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(q));
            
            #line default
            #line hidden
            this.Write(":\r\n");
            
            #line 27 "C:\GitHub\Automata\src\Automata\Templates\AutomatonMovesTextTemplate.tt"
      }
        if (isFinalSink(q))
        {
            
            #line default
            #line hidden
            this.Write("                return true;\r\n");
            
            #line 31 "C:\GitHub\Automata\src\Automata\Templates\AutomatonMovesTextTemplate.tt"
      }
        else if (isNonfinalSink(q))
        {
            
            #line default
            #line hidden
            this.Write("                return false;\r\n");
            
            #line 35 "C:\GitHub\Automata\src\Automata\Templates\AutomatonMovesTextTemplate.tt"
      }
        else
        {
            
            #line default
            #line hidden
            this.Write("                if (");
            
            #line 38 "C:\GitHub\Automata\src\Automata\Templates\AutomatonMovesTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(isAtEndConditionText));
            
            #line default
            #line hidden
            this.Write(") {\r\n                    return ");
            
            #line 39 "C:\GitHub\Automata\src\Automata\Templates\AutomatonMovesTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(automaton.IsFinalState(q) ? "true" : "false"));
            
            #line default
            #line hidden
            this.Write(";\r\n                }\r\n");
            
            #line 41 "C:\GitHub\Automata\src\Automata\Templates\AutomatonMovesTextTemplate.tt"
          if (automaton.GetMovesCountFrom(q) > 0) //q is a sink
            {
                
            
            #line default
            #line hidden
            
            #line 43 "C:\GitHub\Automata\src\Automata\Templates\AutomatonMovesTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(readNextCharText));
            
            #line default
            #line hidden
            
            #line 43 "C:\GitHub\Automata\src\Automata\Templates\AutomatonMovesTextTemplate.tt"
                  
                //---------------------------------------------------------------------
                //many potential optimizations can be made in generating the conditions
                //---------------------------------------------------------------------
                var path = solver.True;
                foreach (var move in automaton.GetMovesFrom(q))
                {
                    path = solver.MkDiff(path, move.Label);
                    if (path == solver.False) //this is the last else case
                    {
            
            #line default
            #line hidden
            this.Write("                goto State");
            
            #line 53 "C:\GitHub\Automata\src\Automata\Templates\AutomatonMovesTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(move.TargetState));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 54 "C:\GitHub\Automata\src\Automata\Templates\AutomatonMovesTextTemplate.tt"
 
                        qIsComplete = true;
                    }
                    else
                    {
            
            #line default
            #line hidden
            this.Write("                if (");
            
            #line 59 "C:\GitHub\Automata\src\Automata\Templates\AutomatonMovesTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(helperPredicates.GeneratePredicate(move.Label)));
            
            #line default
            #line hidden
            this.Write(")\r\n                    goto State");
            
            #line 60 "C:\GitHub\Automata\src\Automata\Templates\AutomatonMovesTextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(move.TargetState));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 61 "C:\GitHub\Automata\src\Automata\Templates\AutomatonMovesTextTemplate.tt"
                  }
                    if (set.Add(move.TargetState))
                        stack.Push(move.TargetState);
                }
            }
            if (!qIsComplete) {
                //reject the input, this corresponds to q being a partial state 
                //the implicit transition is to a deadend sink state

            
            #line default
            #line hidden
            this.Write("                return false;\r\n");
            
            #line 71 "C:\GitHub\Automata\src\Automata\Templates\AutomatonMovesTextTemplate.tt"
          }
        }
    }
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 74 "C:\GitHub\Automata\src\Automata\Templates\AutomatonMovesTextTemplate.tt"

    public AutomatonMovesTextTemplate(CharSetSolver solver, BDDHelperPredicates helperPredicates, Automaton<BDD> automaton,
        string isAtEndConditionText, string readNextCharText)
    {
        this.solver = solver;
        this.helperPredicates = helperPredicates;
        this.automaton = automaton;
        this.isAtEndConditionText = isAtEndConditionText;
        this.readNextCharText = readNextCharText;
    }

    CharSetSolver solver;
    BDDHelperPredicates helperPredicates;
    Automaton<BDD> automaton;
    string isAtEndConditionText;
    string readNextCharText;

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class AutomatonMovesTextTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
