// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, QUT 2005-2010
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.5.0
// Machine:  MARGUS-X1
// DateTime: 6/8/2016 1:05:14 AM
// UserName: margus
// Input file <mona.y - 6/8/2016 12:58:40 AM>

// options: babel conflicts lines diagnose & report gplex conflicts

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using QUT.Gppg;

namespace Microsoft.Automata.MSO.Mona
{
public enum Tokens {
    error=1,EOF=2,WS1S=3,WS2S=4,M2LSTR=5,M2LTREE=6,
    LT=7,GT=8,LE=9,GE=10,EQ=11,NE=12,
    PLUS=13,MINUS=14,TIMES=15,DIV=16,MOD=17,SETMINUS=18,
    TRUE=19,FALSE=20,NOT=21,AND=22,OR=23,IMPLIES=24,
    EQUIV=25,IN=26,NOTIN=27,SUBSET=28,EMPTY=29,RESTRICT=30,
    EX0=31,EX1=32,EX2=33,ALL0=34,ALL1=35,ALL2=36,
    LET0=37,LET1=38,LET2=39,VAR0=40,VAR1=41,VAR2=42,
    WHERE=43,PREFIX=44,MAX=45,MIN=46,PCONST=47,UNION=48,
    INTER=49,GUIDE=50,UNIVERSE=51,INCLUDE=52,ASSERT=53,EXECUTE=54,
    CONST=55,DEFAULTWHERE1=56,DEFAULTWHERE2=57,TREE=58,MACRO=59,PRED=60,
    ALLPOS=61,TYPE=62,ARROW=63,NAME=64,NUMBER=65,LBRACKET=66,
    RBRACKET=67,LBRACE=68,RBRACE=69,LPAR=70,RPAR=71,COMMA=72,
    COLON=73,SEMICOLON=74,RANGE=75,DOT=76,UP=77,BADCHAR=78,
    maxParseToken=79,COMMENT=80};

// Abstract base class for GPLEX scanners
public abstract class ScanBase : AbstractScanner<object,LexLocationInFile> {
  private LexLocationInFile __yylloc = new LexLocationInFile();
  public override LexLocationInFile yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }

  protected abstract int CurrentSc { get; set; }
  //
  // Override the virtual EolState property if the scanner state is more
  // complicated then a simple copy of the current start state ordinal
  //
  public virtual int EolState { get { return CurrentSc; } set { CurrentSc = value; } }
}

// Interface class for 'colorizing' scanners
public interface IColorScan {
  void SetSource(string source, int offset);
  int GetNext(ref int state, out int start, out int end);
}

// Utility class for encapsulating token information
public class ScanObj {
  public int token;
  public object yylval;
  public LexLocationInFile yylloc;
  public ScanObj( int t, object val, LexLocationInFile loc ) {
    this.token = t; this.yylval = val; this.yylloc = loc;
  }
}

public partial class MonaParser: ShiftReduceParser<object, LexLocationInFile>
{
#pragma warning disable 649
  private static Dictionary<int, string> aliasses;
#pragma warning restore 649
  private static Rule[] rules = new Rule[157];
  private static State[] states = new State[357];
  private static string[] nonTerms = new string[] {
      "program", "$accept", "header", "decls", "decl", "formula", "univargs", 
      "intterm", "names", "univs", "vws", "parameters", "params0", "params1", 
      "params2", "univarg", "term2", "Q0", "Q", "exprs", "term", "term1", "letexpr", 
      "letexprs0", "letexprs1", "letexprs2", "expr", "univs_", "elemslist", "elems", 
      "formula0", };

  static MonaParser() {
    states[0] = new State(new int[]{3,352,4,353,5,354,6,355,19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158,51,200,61,209,53,211,54,213,55,215,56,219,57,225,40,231,41,233,42,237,58,241,59,245,60,344},new int[]{-1,1,-3,3,-4,356,-5,6,-6,10,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[1] = new State(new int[]{2,2});
    states[2] = new State(-1);
    states[3] = new State(new int[]{74,4});
    states[4] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158,51,200,61,209,53,211,54,213,55,215,56,219,57,225,40,231,41,233,42,237,58,241,59,245,60,344},new int[]{-4,5,-5,6,-6,10,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[5] = new State(-2);
    states[6] = new State(new int[]{74,7});
    states[7] = new State(new int[]{2,8,19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158,51,200,61,209,53,211,54,213,55,215,56,219,57,225,40,231,41,233,42,237,58,241,59,245,60,344},new int[]{-4,9,-5,6,-6,10,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[8] = new State(-8);
    states[9] = new State(-9);
    states[10] = new State(new int[]{22,11,23,13,24,15,25,17,74,-10});
    states[11] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,12,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[12] = new State(-90);
    states[13] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,14,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[14] = new State(new int[]{22,11,23,-91,24,-91,25,-91,74,-91,71,-91,72,-91,73,-91});
    states[15] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,16,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[16] = new State(new int[]{22,11,23,13,24,15,25,-92,74,-92,71,-92,72,-92,73,-92});
    states[17] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,18,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[18] = new State(new int[]{22,11,23,13,24,15,25,17,74,-93,71,-93,72,-93,73,-93});
    states[19] = new State(-79);
    states[20] = new State(-80);
    states[21] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,22,-22,24,-17,100,-18,113,-19,119,-21,153,-23,148});
    states[22] = new State(new int[]{71,23,22,11,23,13,24,15,25,17});
    states[23] = new State(-81);
    states[24] = new State(new int[]{71,25,13,26,14,28,15,30,16,32,17,34,8,88,10,90,7,92,9,94,26,96,27,98,11,-118,12,-118});
    states[25] = new State(-126);
    states[26] = new State(new int[]{65,36,70,37,46,39,45,79,64,87},new int[]{-22,27});
    states[27] = new State(new int[]{13,-127,14,-127,15,30,16,32,17,34,8,-127,10,-127,7,-127,9,-127,26,-127,27,-127,11,-127,12,-127,71,-127,75,-127,72,-127,69,-127,22,-127,23,-127,24,-127,25,-127,74,-127,73,-127});
    states[28] = new State(new int[]{65,36,70,37,46,39,45,79,64,87},new int[]{-22,29});
    states[29] = new State(new int[]{13,-128,14,-128,15,30,16,32,17,34,8,-128,10,-128,7,-128,9,-128,26,-128,27,-128,11,-128,12,-128,71,-128,75,-128,72,-128,69,-128,22,-128,23,-128,24,-128,25,-128,74,-128,73,-128});
    states[30] = new State(new int[]{65,36,70,37,46,39,45,79,64,87},new int[]{-22,31});
    states[31] = new State(-129);
    states[32] = new State(new int[]{65,36,70,37,46,39,45,79,64,87},new int[]{-22,33});
    states[33] = new State(-130);
    states[34] = new State(new int[]{65,36,70,37,46,39,45,79,64,87},new int[]{-22,35});
    states[35] = new State(-131);
    states[36] = new State(-125);
    states[37] = new State(new int[]{65,36,70,37,46,39,45,79,64,87},new int[]{-22,38});
    states[38] = new State(new int[]{71,25,13,26,14,28,15,30,16,32,17,34});
    states[39] = new State(new int[]{70,66,68,69,29,81,47,82,64,86},new int[]{-17,40});
    states[40] = new State(new int[]{48,41,49,43,18,45,13,47,14,64,15,-132,16,-132,17,-132,8,-132,10,-132,7,-132,9,-132,26,-132,27,-132,11,-132,12,-132,71,-132,75,-132,72,-132,69,-132,22,-132,23,-132,24,-132,25,-132,74,-132,73,-132});
    states[41] = new State(new int[]{70,66,68,69,29,81,47,82,64,86},new int[]{-17,42});
    states[42] = new State(new int[]{48,-140,49,43,18,45,13,47,14,64,28,-140,11,-140,12,-140,71,-140,15,-140,16,-140,17,-140,8,-140,10,-140,7,-140,9,-140,26,-140,27,-140,75,-140,72,-140,69,-140,22,-140,23,-140,24,-140,25,-140,74,-140,73,-140});
    states[43] = new State(new int[]{70,66,68,69,29,81,47,82,64,86},new int[]{-17,44});
    states[44] = new State(new int[]{48,-141,49,-141,18,45,13,47,14,64,28,-141,11,-141,12,-141,71,-141,15,-141,16,-141,17,-141,8,-141,10,-141,7,-141,9,-141,26,-141,27,-141,75,-141,72,-141,69,-141,22,-141,23,-141,24,-141,25,-141,74,-141,73,-141});
    states[45] = new State(new int[]{70,66,68,69,29,81,47,82,64,86},new int[]{-17,46});
    states[46] = new State(new int[]{48,-142,49,-142,18,-142,13,47,14,64,28,-142,11,-142,12,-142,71,-142,15,-142,16,-142,17,-142,8,-142,10,-142,7,-142,9,-142,26,-142,27,-142,75,-142,72,-142,69,-142,22,-142,23,-142,24,-142,25,-142,74,-142,73,-142});
    states[47] = new State(new int[]{70,59,64,62,65,63},new int[]{-8,48});
    states[48] = new State(new int[]{13,-143,14,-143,15,53,16,55,17,57,48,-143,49,-143,18,-143,28,-143,11,-143,12,-143,71,-143,8,-143,10,-143,7,-143,9,-143,26,-143,27,-143,75,-143,72,-143,69,-143,22,-143,23,-143,24,-143,25,-143,74,-143,73,-143});
    states[49] = new State(new int[]{70,59,64,62,65,63},new int[]{-8,50});
    states[50] = new State(new int[]{13,-63,14,-63,15,53,16,55,17,57,48,-63,49,-63,18,-63,28,-63,11,-63,12,-63,71,-63,8,-63,10,-63,7,-63,9,-63,26,-63,27,-63,75,-63,72,-63,69,-63,22,-63,23,-63,24,-63,25,-63,74,-63,73,-63});
    states[51] = new State(new int[]{70,59,64,62,65,63},new int[]{-8,52});
    states[52] = new State(new int[]{13,-64,14,-64,15,53,16,55,17,57,48,-64,49,-64,18,-64,28,-64,11,-64,12,-64,71,-64,8,-64,10,-64,7,-64,9,-64,26,-64,27,-64,75,-64,72,-64,69,-64,22,-64,23,-64,24,-64,25,-64,74,-64,73,-64});
    states[53] = new State(new int[]{70,59,64,62,65,63},new int[]{-8,54});
    states[54] = new State(-65);
    states[55] = new State(new int[]{70,59,64,62,65,63},new int[]{-8,56});
    states[56] = new State(-66);
    states[57] = new State(new int[]{70,59,64,62,65,63},new int[]{-8,58});
    states[58] = new State(-67);
    states[59] = new State(new int[]{70,59,64,62,65,63},new int[]{-8,60});
    states[60] = new State(new int[]{71,61,13,49,14,51,15,53,16,55,17,57});
    states[61] = new State(-62);
    states[62] = new State(-68);
    states[63] = new State(-69);
    states[64] = new State(new int[]{70,59,64,62,65,63},new int[]{-8,65});
    states[65] = new State(new int[]{13,-144,14,-144,15,53,16,55,17,57,48,-144,49,-144,18,-144,28,-144,11,-144,12,-144,71,-144,8,-144,10,-144,7,-144,9,-144,26,-144,27,-144,75,-144,72,-144,69,-144,22,-144,23,-144,24,-144,25,-144,74,-144,73,-144});
    states[66] = new State(new int[]{70,66,68,69,29,81,47,82,64,86},new int[]{-17,67});
    states[67] = new State(new int[]{71,68,48,41,49,43,18,45,13,47,14,64});
    states[68] = new State(-135);
    states[69] = new State(new int[]{69,70,65,36,70,37,46,39,45,79,64,87},new int[]{-29,71,-30,73,-22,76});
    states[70] = new State(-136);
    states[71] = new State(new int[]{69,72});
    states[72] = new State(-137);
    states[73] = new State(new int[]{72,74,69,-147});
    states[74] = new State(new int[]{65,36,70,37,46,39,45,79,64,87},new int[]{-29,75,-30,73,-22,76});
    states[75] = new State(-146);
    states[76] = new State(new int[]{75,77,13,26,14,28,15,30,16,32,17,34,72,-149,69,-149});
    states[77] = new State(new int[]{65,36,70,37,46,39,45,79,64,87},new int[]{-22,78});
    states[78] = new State(new int[]{13,26,14,28,15,30,16,32,17,34,72,-148,69,-148});
    states[79] = new State(new int[]{70,66,68,69,29,81,47,82,64,86},new int[]{-17,80});
    states[80] = new State(new int[]{48,41,49,43,18,45,13,47,14,64,15,-133,16,-133,17,-133,8,-133,10,-133,7,-133,9,-133,26,-133,27,-133,11,-133,12,-133,71,-133,75,-133,72,-133,69,-133,22,-133,23,-133,24,-133,25,-133,74,-133,73,-133});
    states[81] = new State(-138);
    states[82] = new State(new int[]{70,83});
    states[83] = new State(new int[]{70,59,64,62,65,63},new int[]{-8,84});
    states[84] = new State(new int[]{71,85,13,49,14,51,15,53,16,55,17,57});
    states[85] = new State(-139);
    states[86] = new State(-145);
    states[87] = new State(-134);
    states[88] = new State(new int[]{65,36,70,37,46,39,45,79,64,87},new int[]{-22,89});
    states[89] = new State(new int[]{13,26,14,28,15,30,16,32,17,34,22,-96,23,-96,24,-96,25,-96,74,-96,71,-96,72,-96,73,-96});
    states[90] = new State(new int[]{65,36,70,37,46,39,45,79,64,87},new int[]{-22,91});
    states[91] = new State(new int[]{13,26,14,28,15,30,16,32,17,34,22,-97,23,-97,24,-97,25,-97,74,-97,71,-97,72,-97,73,-97});
    states[92] = new State(new int[]{65,36,70,37,46,39,45,79,64,87},new int[]{-22,93});
    states[93] = new State(new int[]{13,26,14,28,15,30,16,32,17,34,22,-98,23,-98,24,-98,25,-98,74,-98,71,-98,72,-98,73,-98});
    states[94] = new State(new int[]{65,36,70,37,46,39,45,79,64,87},new int[]{-22,95});
    states[95] = new State(new int[]{13,26,14,28,15,30,16,32,17,34,22,-99,23,-99,24,-99,25,-99,74,-99,71,-99,72,-99,73,-99});
    states[96] = new State(new int[]{70,66,68,69,29,81,47,82,64,86},new int[]{-17,97});
    states[97] = new State(new int[]{48,41,49,43,18,45,13,47,14,64,22,-100,23,-100,24,-100,25,-100,74,-100,71,-100,72,-100,73,-100});
    states[98] = new State(new int[]{70,66,68,69,29,81,47,82,64,86},new int[]{-17,99});
    states[99] = new State(new int[]{48,41,49,43,18,45,13,47,14,64,22,-101,23,-101,24,-101,25,-101,74,-101,71,-101,72,-101,73,-101});
    states[100] = new State(new int[]{71,68,48,41,49,43,18,45,13,47,14,64,28,101,11,-119,12,-119});
    states[101] = new State(new int[]{70,66,68,69,29,81,47,82,64,86},new int[]{-17,102});
    states[102] = new State(new int[]{48,41,49,43,18,45,13,47,14,64,22,-102,23,-102,24,-102,25,-102,74,-102,71,-102,72,-102,73,-102});
    states[103] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,104,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[104] = new State(-82);
    states[105] = new State(new int[]{70,106});
    states[106] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,107,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[107] = new State(new int[]{71,108,22,11,23,13,24,15,25,17});
    states[108] = new State(-83);
    states[109] = new State(new int[]{70,110,48,-138,49,-138,18,-138,13,-138,14,-138,28,-138,11,-138,12,-138,71,-138,72,-138});
    states[110] = new State(new int[]{70,66,68,69,29,81,47,82,64,86},new int[]{-17,111});
    states[111] = new State(new int[]{71,112,48,41,49,43,18,45,13,47,14,64});
    states[112] = new State(-84);
    states[113] = new State(new int[]{64,197},new int[]{-9,114});
    states[114] = new State(new int[]{73,115});
    states[115] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,116,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[116] = new State(new int[]{22,11,23,13,24,15,25,17,74,-85,71,-85,72,-85,73,-85});
    states[117] = new State(-112);
    states[118] = new State(-113);
    states[119] = new State(new int[]{66,190,64,180},new int[]{-10,120,-11,187});
    states[120] = new State(new int[]{64,180},new int[]{-11,121});
    states[121] = new State(new int[]{73,122});
    states[122] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,123,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[123] = new State(new int[]{22,11,23,13,24,15,25,17,74,-86,71,-86,72,-86,73,-86});
    states[124] = new State(-108);
    states[125] = new State(-109);
    states[126] = new State(-110);
    states[127] = new State(-111);
    states[128] = new State(new int[]{70,129,13,-134,14,-134,15,-134,16,-134,17,-134,8,-134,10,-134,7,-134,9,-134,26,-134,27,-134,11,-134,12,-134,71,-104,72,-104,48,-145,49,-145,18,-145,28,-145,22,-104,23,-104,24,-104,25,-104,74,-104,73,-104});
    states[129] = new State(new int[]{71,130,65,36,70,21,46,39,45,79,64,128,68,69,29,109,47,82,19,19,20,20,21,103,30,105,31,117,34,118,32,124,33,125,35,126,36,127,37,149,38,154,39,158},new int[]{-20,131,-27,133,-21,136,-22,145,-17,146,-6,147,-18,113,-19,119,-23,148});
    states[130] = new State(-88);
    states[131] = new State(new int[]{71,132});
    states[132] = new State(-89);
    states[133] = new State(new int[]{72,134,71,-115});
    states[134] = new State(new int[]{65,36,70,21,46,39,45,79,64,128,68,69,29,109,47,82,19,19,20,20,21,103,30,105,31,117,34,118,32,124,33,125,35,126,36,127,37,149,38,154,39,158},new int[]{-20,135,-27,133,-21,136,-22,145,-17,146,-6,147,-18,113,-19,119,-23,148});
    states[135] = new State(-114);
    states[136] = new State(new int[]{11,137,12,143,72,-116,71,-116});
    states[137] = new State(new int[]{65,36,70,140,46,39,45,79,64,141,68,69,29,81,47,82},new int[]{-21,138,-22,139,-17,142});
    states[138] = new State(-94);
    states[139] = new State(new int[]{13,26,14,28,15,30,16,32,17,34,22,-118,23,-118,24,-118,25,-118,74,-118,71,-118,72,-118,73,-118});
    states[140] = new State(new int[]{65,36,70,140,46,39,45,79,64,141,68,69,29,81,47,82},new int[]{-22,38,-17,67});
    states[141] = new State(new int[]{13,-134,14,-134,15,-134,16,-134,17,-134,22,-134,23,-134,24,-134,25,-134,74,-134,71,-134,72,-134,73,-134,48,-145,49,-145,18,-145});
    states[142] = new State(new int[]{48,41,49,43,18,45,13,47,14,64,22,-119,23,-119,24,-119,25,-119,74,-119,71,-119,72,-119,73,-119});
    states[143] = new State(new int[]{65,36,70,140,46,39,45,79,64,141,68,69,29,81,47,82},new int[]{-21,144,-22,139,-17,142});
    states[144] = new State(-95);
    states[145] = new State(new int[]{13,26,14,28,15,30,16,32,17,34,8,88,10,90,7,92,9,94,26,96,27,98,11,-118,12,-118,72,-118,71,-118});
    states[146] = new State(new int[]{48,41,49,43,18,45,13,47,14,64,28,101,11,-119,12,-119,72,-119,71,-119});
    states[147] = new State(new int[]{22,11,23,13,24,15,25,17,72,-117,71,-117});
    states[148] = new State(-103);
    states[149] = new State(new int[]{64,172},new int[]{-24,150});
    states[150] = new State(new int[]{26,151});
    states[151] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,152,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[152] = new State(-105);
    states[153] = new State(new int[]{11,137,12,143});
    states[154] = new State(new int[]{64,167},new int[]{-25,155});
    states[155] = new State(new int[]{26,156});
    states[156] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,157,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[157] = new State(-106);
    states[158] = new State(new int[]{64,162},new int[]{-26,159});
    states[159] = new State(new int[]{26,160});
    states[160] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,161,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[161] = new State(-107);
    states[162] = new State(new int[]{11,163});
    states[163] = new State(new int[]{70,66,68,69,29,81,47,82,64,86},new int[]{-17,164});
    states[164] = new State(new int[]{72,165,48,41,49,43,18,45,13,47,14,64,26,-155});
    states[165] = new State(new int[]{64,162},new int[]{-26,166});
    states[166] = new State(-154);
    states[167] = new State(new int[]{11,168});
    states[168] = new State(new int[]{65,36,70,37,46,39,45,79,64,87},new int[]{-22,169});
    states[169] = new State(new int[]{72,170,13,26,14,28,15,30,16,32,17,34,26,-153});
    states[170] = new State(new int[]{64,167},new int[]{-25,171});
    states[171] = new State(-152);
    states[172] = new State(new int[]{11,173});
    states[173] = new State(new int[]{70,177},new int[]{-31,174});
    states[174] = new State(new int[]{72,175,26,-151});
    states[175] = new State(new int[]{64,172},new int[]{-24,176});
    states[176] = new State(-150);
    states[177] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,178,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[178] = new State(new int[]{71,179,22,11,23,13,24,15,25,17});
    states[179] = new State(-156);
    states[180] = new State(new int[]{72,181,43,183,73,-78,74,-78});
    states[181] = new State(new int[]{64,180},new int[]{-11,182});
    states[182] = new State(-75);
    states[183] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,184,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[184] = new State(new int[]{72,185,22,11,23,13,24,15,25,17,73,-77,74,-77});
    states[185] = new State(new int[]{64,180},new int[]{-11,186});
    states[186] = new State(-76);
    states[187] = new State(new int[]{73,188});
    states[188] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,189,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[189] = new State(new int[]{22,11,23,13,24,15,25,17,74,-87,71,-87,72,-87,73,-87});
    states[190] = new State(new int[]{64,191});
    states[191] = new State(new int[]{67,193,72,194},new int[]{-28,192});
    states[192] = new State(-122);
    states[193] = new State(-123);
    states[194] = new State(new int[]{64,195});
    states[195] = new State(new int[]{67,193,72,194},new int[]{-28,196});
    states[196] = new State(-124);
    states[197] = new State(new int[]{72,198,73,-121,74,-121});
    states[198] = new State(new int[]{64,197},new int[]{-9,199});
    states[199] = new State(-120);
    states[200] = new State(new int[]{64,205},new int[]{-7,201,-16,202});
    states[201] = new State(-11);
    states[202] = new State(new int[]{72,203,74,-71});
    states[203] = new State(new int[]{64,205},new int[]{-7,204,-16,202});
    states[204] = new State(-70);
    states[205] = new State(new int[]{73,206,72,-74,74,-74});
    states[206] = new State(new int[]{64,207,65,208});
    states[207] = new State(-72);
    states[208] = new State(-73);
    states[209] = new State(new int[]{64,210});
    states[210] = new State(-12);
    states[211] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,212,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[212] = new State(new int[]{22,11,23,13,24,15,25,17,74,-13});
    states[213] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,214,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[214] = new State(new int[]{22,11,23,13,24,15,25,17,74,-14});
    states[215] = new State(new int[]{64,216});
    states[216] = new State(new int[]{11,217});
    states[217] = new State(new int[]{70,59,64,62,65,63},new int[]{-8,218});
    states[218] = new State(new int[]{13,49,14,51,15,53,16,55,17,57,74,-15});
    states[219] = new State(new int[]{70,220});
    states[220] = new State(new int[]{64,221});
    states[221] = new State(new int[]{71,222});
    states[222] = new State(new int[]{11,223});
    states[223] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,224,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[224] = new State(new int[]{22,11,23,13,24,15,25,17,74,-16});
    states[225] = new State(new int[]{70,226});
    states[226] = new State(new int[]{64,227});
    states[227] = new State(new int[]{71,228});
    states[228] = new State(new int[]{11,229});
    states[229] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,230,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[230] = new State(new int[]{22,11,23,13,24,15,25,17,74,-17});
    states[231] = new State(new int[]{64,197},new int[]{-9,232});
    states[232] = new State(-18);
    states[233] = new State(new int[]{66,190,64,180},new int[]{-10,234,-11,236});
    states[234] = new State(new int[]{64,180},new int[]{-11,235});
    states[235] = new State(-19);
    states[236] = new State(-22);
    states[237] = new State(new int[]{66,190,64,180},new int[]{-10,238,-11,240});
    states[238] = new State(new int[]{64,180},new int[]{-11,239});
    states[239] = new State(-20);
    states[240] = new State(-23);
    states[241] = new State(new int[]{66,190,64,180},new int[]{-10,242,-11,244});
    states[242] = new State(new int[]{64,180},new int[]{-11,243});
    states[243] = new State(-21);
    states[244] = new State(-24);
    states[245] = new State(new int[]{64,246});
    states[246] = new State(new int[]{11,247,70,249});
    states[247] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,248,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[248] = new State(new int[]{22,11,23,13,24,15,25,17,74,-25});
    states[249] = new State(new int[]{71,253,40,254,51,305,41,308,42,314},new int[]{-12,250});
    states[250] = new State(new int[]{11,251});
    states[251] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,252,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[252] = new State(new int[]{22,11,23,13,24,15,25,17,74,-26});
    states[253] = new State(-29);
    states[254] = new State(new int[]{64,255});
    states[255] = new State(new int[]{71,257,72,258},new int[]{-13,256});
    states[256] = new State(-30);
    states[257] = new State(-36);
    states[258] = new State(new int[]{40,259,41,262,42,333,51,339,64,342});
    states[259] = new State(new int[]{64,260});
    states[260] = new State(new int[]{71,257,72,258},new int[]{-13,261});
    states[261] = new State(-37);
    states[262] = new State(new int[]{64,263});
    states[263] = new State(new int[]{43,265,71,268,72,269},new int[]{-14,264});
    states[264] = new State(-38);
    states[265] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,266,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[266] = new State(new int[]{22,11,23,13,24,15,25,17,71,268,72,269},new int[]{-14,267});
    states[267] = new State(-39);
    states[268] = new State(-44);
    states[269] = new State(new int[]{40,270,41,273,42,279,51,325,64,328});
    states[270] = new State(new int[]{64,271});
    states[271] = new State(new int[]{71,257,72,258},new int[]{-13,272});
    states[272] = new State(-45);
    states[273] = new State(new int[]{64,274});
    states[274] = new State(new int[]{43,276,71,268,72,269},new int[]{-14,275});
    states[275] = new State(-46);
    states[276] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,277,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[277] = new State(new int[]{22,11,23,13,24,15,25,17,71,268,72,269},new int[]{-14,278});
    states[278] = new State(-47);
    states[279] = new State(new int[]{64,280});
    states[280] = new State(new int[]{43,282,71,285,72,286},new int[]{-15,281});
    states[281] = new State(-48);
    states[282] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,283,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[283] = new State(new int[]{22,11,23,13,24,15,25,17,71,285,72,286},new int[]{-15,284});
    states[284] = new State(-49);
    states[285] = new State(-53);
    states[286] = new State(new int[]{40,287,41,290,42,296,51,302,64,320});
    states[287] = new State(new int[]{64,288});
    states[288] = new State(new int[]{71,257,72,258},new int[]{-13,289});
    states[289] = new State(-54);
    states[290] = new State(new int[]{64,291});
    states[291] = new State(new int[]{43,293,71,268,72,269},new int[]{-14,292});
    states[292] = new State(-55);
    states[293] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,294,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[294] = new State(new int[]{22,11,23,13,24,15,25,17,71,268,72,269},new int[]{-14,295});
    states[295] = new State(-56);
    states[296] = new State(new int[]{64,297});
    states[297] = new State(new int[]{43,299,71,285,72,286},new int[]{-15,298});
    states[298] = new State(-57);
    states[299] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,300,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[300] = new State(new int[]{22,11,23,13,24,15,25,17,71,285,72,286},new int[]{-15,301});
    states[301] = new State(-58);
    states[302] = new State(new int[]{64,303});
    states[303] = new State(new int[]{71,253,40,254,51,305,41,308,42,314},new int[]{-12,304});
    states[304] = new State(-59);
    states[305] = new State(new int[]{64,306});
    states[306] = new State(new int[]{71,253,40,254,51,305,41,308,42,314},new int[]{-12,307});
    states[307] = new State(-31);
    states[308] = new State(new int[]{64,309});
    states[309] = new State(new int[]{43,311,71,268,72,269},new int[]{-14,310});
    states[310] = new State(-32);
    states[311] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,312,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[312] = new State(new int[]{22,11,23,13,24,15,25,17,71,268,72,269},new int[]{-14,313});
    states[313] = new State(-33);
    states[314] = new State(new int[]{64,315});
    states[315] = new State(new int[]{43,317,71,285,72,286},new int[]{-15,316});
    states[316] = new State(-34);
    states[317] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,318,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[318] = new State(new int[]{22,11,23,13,24,15,25,17,71,285,72,286},new int[]{-15,319});
    states[319] = new State(-35);
    states[320] = new State(new int[]{43,322,71,285,72,286},new int[]{-15,321});
    states[321] = new State(-60);
    states[322] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,323,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[323] = new State(new int[]{22,11,23,13,24,15,25,17,71,285,72,286},new int[]{-15,324});
    states[324] = new State(-61);
    states[325] = new State(new int[]{64,326});
    states[326] = new State(new int[]{71,253,40,254,51,305,41,308,42,314},new int[]{-12,327});
    states[327] = new State(-50);
    states[328] = new State(new int[]{43,330,71,268,72,269},new int[]{-14,329});
    states[329] = new State(-51);
    states[330] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,331,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[331] = new State(new int[]{22,11,23,13,24,15,25,17,71,268,72,269},new int[]{-14,332});
    states[332] = new State(-52);
    states[333] = new State(new int[]{64,334});
    states[334] = new State(new int[]{43,336,71,285,72,286},new int[]{-15,335});
    states[335] = new State(-40);
    states[336] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,337,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[337] = new State(new int[]{22,11,23,13,24,15,25,17,71,285,72,286},new int[]{-15,338});
    states[338] = new State(-41);
    states[339] = new State(new int[]{64,340});
    states[340] = new State(new int[]{71,253,40,254,51,305,41,308,42,314},new int[]{-12,341});
    states[341] = new State(-42);
    states[342] = new State(new int[]{71,257,72,258},new int[]{-13,343});
    states[343] = new State(-43);
    states[344] = new State(new int[]{64,345});
    states[345] = new State(new int[]{11,346,70,348});
    states[346] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,347,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[347] = new State(new int[]{22,11,23,13,24,15,25,17,74,-27});
    states[348] = new State(new int[]{71,253,40,254,51,305,41,308,42,314},new int[]{-12,349});
    states[349] = new State(new int[]{11,350});
    states[350] = new State(new int[]{19,19,20,20,70,21,21,103,30,105,29,109,31,117,34,118,32,124,33,125,35,126,36,127,64,128,65,36,46,39,45,79,68,69,47,82,37,149,38,154,39,158},new int[]{-6,351,-18,113,-19,119,-21,153,-22,145,-17,146,-23,148});
    states[351] = new State(new int[]{22,11,23,13,24,15,25,17,74,-28});
    states[352] = new State(-4);
    states[353] = new State(-5);
    states[354] = new State(-6);
    states[355] = new State(-7);
    states[356] = new State(-3);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-2, new int[]{-1,2});
    rules[2] = new Rule(-1, new int[]{-3,74,-4});
    rules[3] = new Rule(-1, new int[]{-4});
    rules[4] = new Rule(-3, new int[]{3});
    rules[5] = new Rule(-3, new int[]{4});
    rules[6] = new Rule(-3, new int[]{5});
    rules[7] = new Rule(-3, new int[]{6});
    rules[8] = new Rule(-4, new int[]{-5,74,2});
    rules[9] = new Rule(-4, new int[]{-5,74,-4});
    rules[10] = new Rule(-5, new int[]{-6});
    rules[11] = new Rule(-5, new int[]{51,-7});
    rules[12] = new Rule(-5, new int[]{61,64});
    rules[13] = new Rule(-5, new int[]{53,-6});
    rules[14] = new Rule(-5, new int[]{54,-6});
    rules[15] = new Rule(-5, new int[]{55,64,11,-8});
    rules[16] = new Rule(-5, new int[]{56,70,64,71,11,-6});
    rules[17] = new Rule(-5, new int[]{57,70,64,71,11,-6});
    rules[18] = new Rule(-5, new int[]{40,-9});
    rules[19] = new Rule(-5, new int[]{41,-10,-11});
    rules[20] = new Rule(-5, new int[]{42,-10,-11});
    rules[21] = new Rule(-5, new int[]{58,-10,-11});
    rules[22] = new Rule(-5, new int[]{41,-11});
    rules[23] = new Rule(-5, new int[]{42,-11});
    rules[24] = new Rule(-5, new int[]{58,-11});
    rules[25] = new Rule(-5, new int[]{59,64,11,-6});
    rules[26] = new Rule(-5, new int[]{59,64,70,-12,11,-6});
    rules[27] = new Rule(-5, new int[]{60,64,11,-6});
    rules[28] = new Rule(-5, new int[]{60,64,70,-12,11,-6});
    rules[29] = new Rule(-12, new int[]{71});
    rules[30] = new Rule(-12, new int[]{40,64,-13});
    rules[31] = new Rule(-12, new int[]{51,64,-12});
    rules[32] = new Rule(-12, new int[]{41,64,-14});
    rules[33] = new Rule(-12, new int[]{41,64,43,-6,-14});
    rules[34] = new Rule(-12, new int[]{42,64,-15});
    rules[35] = new Rule(-12, new int[]{42,64,43,-6,-15});
    rules[36] = new Rule(-13, new int[]{71});
    rules[37] = new Rule(-13, new int[]{72,40,64,-13});
    rules[38] = new Rule(-13, new int[]{72,41,64,-14});
    rules[39] = new Rule(-13, new int[]{72,41,64,43,-6,-14});
    rules[40] = new Rule(-13, new int[]{72,42,64,-15});
    rules[41] = new Rule(-13, new int[]{72,42,64,43,-6,-15});
    rules[42] = new Rule(-13, new int[]{72,51,64,-12});
    rules[43] = new Rule(-13, new int[]{72,64,-13});
    rules[44] = new Rule(-14, new int[]{71});
    rules[45] = new Rule(-14, new int[]{72,40,64,-13});
    rules[46] = new Rule(-14, new int[]{72,41,64,-14});
    rules[47] = new Rule(-14, new int[]{72,41,64,43,-6,-14});
    rules[48] = new Rule(-14, new int[]{72,42,64,-15});
    rules[49] = new Rule(-14, new int[]{72,42,64,43,-6,-15});
    rules[50] = new Rule(-14, new int[]{72,51,64,-12});
    rules[51] = new Rule(-14, new int[]{72,64,-14});
    rules[52] = new Rule(-14, new int[]{72,64,43,-6,-14});
    rules[53] = new Rule(-15, new int[]{71});
    rules[54] = new Rule(-15, new int[]{72,40,64,-13});
    rules[55] = new Rule(-15, new int[]{72,41,64,-14});
    rules[56] = new Rule(-15, new int[]{72,41,64,43,-6,-14});
    rules[57] = new Rule(-15, new int[]{72,42,64,-15});
    rules[58] = new Rule(-15, new int[]{72,42,64,43,-6,-15});
    rules[59] = new Rule(-15, new int[]{72,51,64,-12});
    rules[60] = new Rule(-15, new int[]{72,64,-15});
    rules[61] = new Rule(-15, new int[]{72,64,43,-6,-15});
    rules[62] = new Rule(-8, new int[]{70,-8,71});
    rules[63] = new Rule(-8, new int[]{-8,13,-8});
    rules[64] = new Rule(-8, new int[]{-8,14,-8});
    rules[65] = new Rule(-8, new int[]{-8,15,-8});
    rules[66] = new Rule(-8, new int[]{-8,16,-8});
    rules[67] = new Rule(-8, new int[]{-8,17,-8});
    rules[68] = new Rule(-8, new int[]{64});
    rules[69] = new Rule(-8, new int[]{65});
    rules[70] = new Rule(-7, new int[]{-16,72,-7});
    rules[71] = new Rule(-7, new int[]{-16});
    rules[72] = new Rule(-16, new int[]{64,73,64});
    rules[73] = new Rule(-16, new int[]{64,73,65});
    rules[74] = new Rule(-16, new int[]{64});
    rules[75] = new Rule(-11, new int[]{64,72,-11});
    rules[76] = new Rule(-11, new int[]{64,43,-6,72,-11});
    rules[77] = new Rule(-11, new int[]{64,43,-6});
    rules[78] = new Rule(-11, new int[]{64});
    rules[79] = new Rule(-6, new int[]{19});
    rules[80] = new Rule(-6, new int[]{20});
    rules[81] = new Rule(-6, new int[]{70,-6,71});
    rules[82] = new Rule(-6, new int[]{21,-6});
    rules[83] = new Rule(-6, new int[]{30,70,-6,71});
    rules[84] = new Rule(-6, new int[]{29,70,-17,71});
    rules[85] = new Rule(-6, new int[]{-18,-9,73,-6});
    rules[86] = new Rule(-6, new int[]{-19,-10,-11,73,-6});
    rules[87] = new Rule(-6, new int[]{-19,-11,73,-6});
    rules[88] = new Rule(-6, new int[]{64,70,71});
    rules[89] = new Rule(-6, new int[]{64,70,-20,71});
    rules[90] = new Rule(-6, new int[]{-6,22,-6});
    rules[91] = new Rule(-6, new int[]{-6,23,-6});
    rules[92] = new Rule(-6, new int[]{-6,24,-6});
    rules[93] = new Rule(-6, new int[]{-6,25,-6});
    rules[94] = new Rule(-6, new int[]{-21,11,-21});
    rules[95] = new Rule(-6, new int[]{-21,12,-21});
    rules[96] = new Rule(-6, new int[]{-22,8,-22});
    rules[97] = new Rule(-6, new int[]{-22,10,-22});
    rules[98] = new Rule(-6, new int[]{-22,7,-22});
    rules[99] = new Rule(-6, new int[]{-22,9,-22});
    rules[100] = new Rule(-6, new int[]{-22,26,-17});
    rules[101] = new Rule(-6, new int[]{-22,27,-17});
    rules[102] = new Rule(-6, new int[]{-17,28,-17});
    rules[103] = new Rule(-6, new int[]{-23});
    rules[104] = new Rule(-6, new int[]{64});
    rules[105] = new Rule(-23, new int[]{37,-24,26,-6});
    rules[106] = new Rule(-23, new int[]{38,-25,26,-6});
    rules[107] = new Rule(-23, new int[]{39,-26,26,-6});
    rules[108] = new Rule(-19, new int[]{32});
    rules[109] = new Rule(-19, new int[]{33});
    rules[110] = new Rule(-19, new int[]{35});
    rules[111] = new Rule(-19, new int[]{36});
    rules[112] = new Rule(-18, new int[]{31});
    rules[113] = new Rule(-18, new int[]{34});
    rules[114] = new Rule(-20, new int[]{-27,72,-20});
    rules[115] = new Rule(-20, new int[]{-27});
    rules[116] = new Rule(-27, new int[]{-21});
    rules[117] = new Rule(-27, new int[]{-6});
    rules[118] = new Rule(-21, new int[]{-22});
    rules[119] = new Rule(-21, new int[]{-17});
    rules[120] = new Rule(-9, new int[]{64,72,-9});
    rules[121] = new Rule(-9, new int[]{64});
    rules[122] = new Rule(-10, new int[]{66,64,-28});
    rules[123] = new Rule(-28, new int[]{67});
    rules[124] = new Rule(-28, new int[]{72,64,-28});
    rules[125] = new Rule(-22, new int[]{65});
    rules[126] = new Rule(-22, new int[]{70,-22,71});
    rules[127] = new Rule(-22, new int[]{-22,13,-22});
    rules[128] = new Rule(-22, new int[]{-22,14,-22});
    rules[129] = new Rule(-22, new int[]{-22,15,-22});
    rules[130] = new Rule(-22, new int[]{-22,16,-22});
    rules[131] = new Rule(-22, new int[]{-22,17,-22});
    rules[132] = new Rule(-22, new int[]{46,-17});
    rules[133] = new Rule(-22, new int[]{45,-17});
    rules[134] = new Rule(-22, new int[]{64});
    rules[135] = new Rule(-17, new int[]{70,-17,71});
    rules[136] = new Rule(-17, new int[]{68,69});
    rules[137] = new Rule(-17, new int[]{68,-29,69});
    rules[138] = new Rule(-17, new int[]{29});
    rules[139] = new Rule(-17, new int[]{47,70,-8,71});
    rules[140] = new Rule(-17, new int[]{-17,48,-17});
    rules[141] = new Rule(-17, new int[]{-17,49,-17});
    rules[142] = new Rule(-17, new int[]{-17,18,-17});
    rules[143] = new Rule(-17, new int[]{-17,13,-8});
    rules[144] = new Rule(-17, new int[]{-17,14,-8});
    rules[145] = new Rule(-17, new int[]{64});
    rules[146] = new Rule(-29, new int[]{-30,72,-29});
    rules[147] = new Rule(-29, new int[]{-30});
    rules[148] = new Rule(-30, new int[]{-22,75,-22});
    rules[149] = new Rule(-30, new int[]{-22});
    rules[150] = new Rule(-24, new int[]{64,11,-31,72,-24});
    rules[151] = new Rule(-24, new int[]{64,11,-31});
    rules[152] = new Rule(-25, new int[]{64,11,-22,72,-25});
    rules[153] = new Rule(-25, new int[]{64,11,-22});
    rules[154] = new Rule(-26, new int[]{64,11,-17,72,-26});
    rules[155] = new Rule(-26, new int[]{64,11,-17});
    rules[156] = new Rule(-31, new int[]{70,-6,71});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
      case 2: // program -> header, SEMICOLON, decls
#line 44 "mona.y"
{ CurrentSemanticValue = MkProgram(ValueStack[ValueStack.Depth-1], ValueStack[ValueStack.Depth-3]); }
        break;
      case 3: // program -> decls
#line 45 "mona.y"
{ CurrentSemanticValue = MkProgram(ValueStack[ValueStack.Depth-1], null); }
        break;
      case 8: // decls -> decl, SEMICOLON, EOF
#line 53 "mona.y"
{ CurrentSemanticValue = MkList<MonaDecl>(ValueStack[ValueStack.Depth-3]); }
        break;
      case 9: // decls -> decl, SEMICOLON, decls
#line 54 "mona.y"
{ CurrentSemanticValue = MkList<MonaDecl>(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 10: // decl -> formula
#line 58 "mona.y"
{ CurrentSemanticValue = MkFormulaDecl(ValueStack[ValueStack.Depth-1]); }
        break;
      case 11: // decl -> UNIVERSE, univargs
#line 59 "mona.y"
{ CurrentSemanticValue = MkUnivDecl(ValueStack[ValueStack.Depth-1]); }
        break;
      case 12: // decl -> ALLPOS, NAME
#line 60 "mona.y"
{ CurrentSemanticValue = MkAllposDecl(ValueStack[ValueStack.Depth-1]); }
        break;
      case 13: // decl -> ASSERT, formula
#line 61 "mona.y"
{ CurrentSemanticValue = MkAssertDecl(ValueStack[ValueStack.Depth-1]); }
        break;
      case 14: // decl -> EXECUTE, formula
#line 62 "mona.y"
{ CurrentSemanticValue = MkExecuteDecl(ValueStack[ValueStack.Depth-1]); }
        break;
      case 15: // decl -> CONST, NAME, EQ, intterm
#line 63 "mona.y"
{ CurrentSemanticValue = MkConstDecl(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 16: // decl -> DEFAULTWHERE1, LPAR, NAME, RPAR, EQ, formula
#line 64 "mona.y"
{ CurrentSemanticValue = MkDefaultWhere1Decl(ValueStack[ValueStack.Depth-4], ValueStack[ValueStack.Depth-1]); }
        break;
      case 17: // decl -> DEFAULTWHERE2, LPAR, NAME, RPAR, EQ, formula
#line 65 "mona.y"
{ CurrentSemanticValue = MkDefaultWhere2Decl(ValueStack[ValueStack.Depth-4], ValueStack[ValueStack.Depth-1]); }
        break;
      case 18: // decl -> VAR0, names
#line 66 "mona.y"
{ CurrentSemanticValue = MkVar0Decl(ValueStack[ValueStack.Depth-1]); }
        break;
      case 19: // decl -> VAR1, univs, vws
#line 67 "mona.y"
{ CurrentSemanticValue = MkVar1Decl(ValueStack[ValueStack.Depth-1], ValueStack[ValueStack.Depth-2]); }
        break;
      case 20: // decl -> VAR2, univs, vws
#line 68 "mona.y"
{ CurrentSemanticValue = MkVar2Decl(ValueStack[ValueStack.Depth-1], ValueStack[ValueStack.Depth-2]); }
        break;
      case 21: // decl -> TREE, univs, vws
#line 69 "mona.y"
{ CurrentSemanticValue = MkTreeDecl(ValueStack[ValueStack.Depth-1], ValueStack[ValueStack.Depth-2]); }
        break;
      case 22: // decl -> VAR1, vws
#line 70 "mona.y"
{ CurrentSemanticValue = MkVar1Decl(ValueStack[ValueStack.Depth-1], null); }
        break;
      case 23: // decl -> VAR2, vws
#line 71 "mona.y"
{ CurrentSemanticValue = MkVar2Decl(ValueStack[ValueStack.Depth-1], null); }
        break;
      case 24: // decl -> TREE, vws
#line 72 "mona.y"
{ CurrentSemanticValue = MkTreeDecl(ValueStack[ValueStack.Depth-1], null); }
        break;
      case 25: // decl -> MACRO, NAME, EQ, formula
#line 73 "mona.y"
{ CurrentSemanticValue = MkPredDecl(ValueStack[ValueStack.Depth-3], null, ValueStack[ValueStack.Depth-1], true); }
        break;
      case 26: // decl -> MACRO, NAME, LPAR, parameters, EQ, formula
#line 74 "mona.y"
{ CurrentSemanticValue = MkPredDecl(ValueStack[ValueStack.Depth-5], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1], true); }
        break;
      case 27: // decl -> PRED, NAME, EQ, formula
#line 75 "mona.y"
{ CurrentSemanticValue = MkPredDecl(ValueStack[ValueStack.Depth-3], null, ValueStack[ValueStack.Depth-1], false); }
        break;
      case 28: // decl -> PRED, NAME, LPAR, parameters, EQ, formula
#line 76 "mona.y"
{ CurrentSemanticValue = MkPredDecl(ValueStack[ValueStack.Depth-5], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1], false); }
        break;
      case 29: // parameters -> RPAR
#line 80 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(); }
        break;
      case 30: // parameters -> VAR0, NAME, params0
#line 81 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(MkVar0Param(ValueStack[ValueStack.Depth-2]), ValueStack[ValueStack.Depth-1]); }
        break;
      case 31: // parameters -> UNIVERSE, NAME, parameters
#line 82 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(MkUniverseParam(ValueStack[ValueStack.Depth-2]), ValueStack[ValueStack.Depth-1]); }
        break;
      case 32: // parameters -> VAR1, NAME, params1
#line 83 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(MkVar1Param(MkVarWhere(ValueStack[ValueStack.Depth-2], null)), ValueStack[ValueStack.Depth-1]); }
        break;
      case 33: // parameters -> VAR1, NAME, WHERE, formula, params1
#line 84 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(MkVar1Param(MkVarWhere(ValueStack[ValueStack.Depth-4], ValueStack[ValueStack.Depth-2])), ValueStack[ValueStack.Depth-1]); }
        break;
      case 34: // parameters -> VAR2, NAME, params2
#line 85 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(MkVar2Param(MkVarWhere(ValueStack[ValueStack.Depth-2], null)), ValueStack[ValueStack.Depth-1]); }
        break;
      case 35: // parameters -> VAR2, NAME, WHERE, formula, params2
#line 86 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(MkVar2Param(MkVarWhere(ValueStack[ValueStack.Depth-4], ValueStack[ValueStack.Depth-2])), ValueStack[ValueStack.Depth-1]); }
        break;
      case 36: // params0 -> RPAR
#line 90 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(); }
        break;
      case 37: // params0 -> COMMA, VAR0, NAME, params0
#line 91 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(MkVar0Param(ValueStack[ValueStack.Depth-2]), ValueStack[ValueStack.Depth-1]); }
        break;
      case 38: // params0 -> COMMA, VAR1, NAME, params1
#line 92 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(MkVar1Param(MkVarWhere(ValueStack[ValueStack.Depth-2], null)), ValueStack[ValueStack.Depth-1]); }
        break;
      case 39: // params0 -> COMMA, VAR1, NAME, WHERE, formula, params1
#line 93 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(MkVar1Param(MkVarWhere(ValueStack[ValueStack.Depth-4], ValueStack[ValueStack.Depth-2])), ValueStack[ValueStack.Depth-1]); }
        break;
      case 40: // params0 -> COMMA, VAR2, NAME, params2
#line 94 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(MkVar2Param(MkVarWhere(ValueStack[ValueStack.Depth-2], null)), ValueStack[ValueStack.Depth-1]); }
        break;
      case 41: // params0 -> COMMA, VAR2, NAME, WHERE, formula, params2
#line 95 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(MkVar2Param(MkVarWhere(ValueStack[ValueStack.Depth-4], ValueStack[ValueStack.Depth-2])), ValueStack[ValueStack.Depth-1]); }
        break;
      case 42: // params0 -> COMMA, UNIVERSE, NAME, parameters
#line 96 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(MkUniverseParam(ValueStack[ValueStack.Depth-2]), ValueStack[ValueStack.Depth-1]); }
        break;
      case 43: // params0 -> COMMA, NAME, params0
#line 97 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(MkVar0Param(ValueStack[ValueStack.Depth-2]), ValueStack[ValueStack.Depth-1]); }
        break;
      case 44: // params1 -> RPAR
#line 101 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(); }
        break;
      case 45: // params1 -> COMMA, VAR0, NAME, params0
#line 102 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(MkVar0Param(ValueStack[ValueStack.Depth-2]), ValueStack[ValueStack.Depth-1]); }
        break;
      case 46: // params1 -> COMMA, VAR1, NAME, params1
#line 103 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(MkVar1Param(MkVarWhere(ValueStack[ValueStack.Depth-2], null)), ValueStack[ValueStack.Depth-1]); }
        break;
      case 47: // params1 -> COMMA, VAR1, NAME, WHERE, formula, params1
#line 104 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(MkVar1Param(MkVarWhere(ValueStack[ValueStack.Depth-4], ValueStack[ValueStack.Depth-2])), ValueStack[ValueStack.Depth-1]); }
        break;
      case 48: // params1 -> COMMA, VAR2, NAME, params2
#line 105 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(MkVar2Param(MkVarWhere(ValueStack[ValueStack.Depth-2], null)), ValueStack[ValueStack.Depth-1]); }
        break;
      case 49: // params1 -> COMMA, VAR2, NAME, WHERE, formula, params2
#line 106 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(MkVar2Param(MkVarWhere(ValueStack[ValueStack.Depth-4], ValueStack[ValueStack.Depth-2])), ValueStack[ValueStack.Depth-1]); }
        break;
      case 50: // params1 -> COMMA, UNIVERSE, NAME, parameters
#line 107 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(MkUniverseParam(ValueStack[ValueStack.Depth-2]), ValueStack[ValueStack.Depth-1]); }
        break;
      case 51: // params1 -> COMMA, NAME, params1
#line 108 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(MkVar1Param(MkVarWhere(ValueStack[ValueStack.Depth-2], null)), ValueStack[ValueStack.Depth-1]); }
        break;
      case 52: // params1 -> COMMA, NAME, WHERE, formula, params1
#line 109 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(MkVar1Param(MkVarWhere(ValueStack[ValueStack.Depth-4], ValueStack[ValueStack.Depth-2])), ValueStack[ValueStack.Depth-1]); }
        break;
      case 53: // params2 -> RPAR
#line 113 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(); }
        break;
      case 54: // params2 -> COMMA, VAR0, NAME, params0
#line 114 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(MkVar0Param(ValueStack[ValueStack.Depth-2]), ValueStack[ValueStack.Depth-1]); }
        break;
      case 55: // params2 -> COMMA, VAR1, NAME, params1
#line 115 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(MkVar1Param(MkVarWhere(ValueStack[ValueStack.Depth-2], null)), ValueStack[ValueStack.Depth-1]); }
        break;
      case 56: // params2 -> COMMA, VAR1, NAME, WHERE, formula, params1
#line 116 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(MkVar1Param(MkVarWhere(ValueStack[ValueStack.Depth-4], ValueStack[ValueStack.Depth-2])), ValueStack[ValueStack.Depth-1]); }
        break;
      case 57: // params2 -> COMMA, VAR2, NAME, params2
#line 117 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(MkVar2Param(MkVarWhere(ValueStack[ValueStack.Depth-2], null)), ValueStack[ValueStack.Depth-1]); }
        break;
      case 58: // params2 -> COMMA, VAR2, NAME, WHERE, formula, params2
#line 118 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(MkVar2Param(MkVarWhere(ValueStack[ValueStack.Depth-4], ValueStack[ValueStack.Depth-2])), ValueStack[ValueStack.Depth-1]); }
        break;
      case 59: // params2 -> COMMA, UNIVERSE, NAME, parameters
#line 119 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(MkUniverseParam(ValueStack[ValueStack.Depth-2]), ValueStack[ValueStack.Depth-1]); }
        break;
      case 60: // params2 -> COMMA, NAME, params2
#line 120 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(MkVar2Param(MkVarWhere(ValueStack[ValueStack.Depth-2], null)), ValueStack[ValueStack.Depth-1]); }
        break;
      case 61: // params2 -> COMMA, NAME, WHERE, formula, params2
#line 121 "mona.y"
{ CurrentSemanticValue = MkList<MonaParam>(MkVar2Param(MkVarWhere(ValueStack[ValueStack.Depth-4], ValueStack[ValueStack.Depth-2])), ValueStack[ValueStack.Depth-1]); }
        break;
      case 62: // intterm -> LPAR, intterm, RPAR
#line 125 "mona.y"
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-2]; }
        break;
      case 63: // intterm -> intterm, PLUS, intterm
#line 126 "mona.y"
{ CurrentSemanticValue = MkArithmFuncApp(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 64: // intterm -> intterm, MINUS, intterm
#line 127 "mona.y"
{ CurrentSemanticValue = MkArithmFuncApp(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 65: // intterm -> intterm, TIMES, intterm
#line 128 "mona.y"
{ CurrentSemanticValue = MkArithmFuncApp(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 66: // intterm -> intterm, DIV, intterm
#line 129 "mona.y"
{ CurrentSemanticValue = MkArithmFuncApp(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 67: // intterm -> intterm, MOD, intterm
#line 130 "mona.y"
{ CurrentSemanticValue = MkArithmFuncApp(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 68: // intterm -> NAME
#line 131 "mona.y"
{ CurrentSemanticValue = MkConstRef(ValueStack[ValueStack.Depth-1]); }
        break;
      case 69: // intterm -> NUMBER
#line 132 "mona.y"
{ CurrentSemanticValue = MkInt(ValueStack[ValueStack.Depth-1]); }
        break;
      case 70: // univargs -> univarg, COMMA, univargs
#line 136 "mona.y"
{ CurrentSemanticValue = MkList<MonaUnivArg>(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 71: // univargs -> univarg
#line 137 "mona.y"
{ CurrentSemanticValue = MkList<MonaUnivArg>(ValueStack[ValueStack.Depth-1]); }
        break;
      case 72: // univarg -> NAME, COLON, NAME
#line 141 "mona.y"
{ CurrentSemanticValue = MkUnivArgWithType(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 73: // univarg -> NAME, COLON, NUMBER
#line 142 "mona.y"
{ CurrentSemanticValue = MkUnivArgWithSucc(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 74: // univarg -> NAME
#line 143 "mona.y"
{ CurrentSemanticValue = MkUnivArg(ValueStack[ValueStack.Depth-1]); }
        break;
      case 75: // vws -> NAME, COMMA, vws
#line 147 "mona.y"
{ CurrentSemanticValue = MkList<MonaVarWhere>(MkVarWhere(ValueStack[ValueStack.Depth-3], null), ValueStack[ValueStack.Depth-1]); }
        break;
      case 76: // vws -> NAME, WHERE, formula, COMMA, vws
#line 148 "mona.y"
{ CurrentSemanticValue = MkList<MonaVarWhere>(MkVarWhere(ValueStack[ValueStack.Depth-5], ValueStack[ValueStack.Depth-3]), ValueStack[ValueStack.Depth-2]); }
        break;
      case 77: // vws -> NAME, WHERE, formula
#line 149 "mona.y"
{ CurrentSemanticValue = MkList<MonaVarWhere>(MkVarWhere(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1])); }
        break;
      case 78: // vws -> NAME
#line 150 "mona.y"
{ CurrentSemanticValue = MkList<MonaVarWhere>(MkVarWhere(ValueStack[ValueStack.Depth-1], null)); }
        break;
      case 79: // formula -> TRUE
#line 154 "mona.y"
{ CurrentSemanticValue = MkBooleanConstant(ValueStack[ValueStack.Depth-1]) ; }
        break;
      case 80: // formula -> FALSE
#line 155 "mona.y"
{ CurrentSemanticValue = MkBooleanConstant(ValueStack[ValueStack.Depth-1]) ; }
        break;
      case 81: // formula -> LPAR, formula, RPAR
#line 156 "mona.y"
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-2]; }
        break;
      case 82: // formula -> NOT, formula
#line 157 "mona.y"
{ CurrentSemanticValue = MkNegatedFormula(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-1]); }
        break;
      case 83: // formula -> RESTRICT, LPAR, formula, RPAR
#line 158 "mona.y"
{ CurrentSemanticValue = MkRestrict(ValueStack[ValueStack.Depth-4], ValueStack[ValueStack.Depth-2]); }
        break;
      case 84: // formula -> EMPTY, LPAR, term2, RPAR
#line 159 "mona.y"
{ CurrentSemanticValue = MkIsEmpty(ValueStack[ValueStack.Depth-4], ValueStack[ValueStack.Depth-2]); }
        break;
      case 85: // formula -> Q0, names, COLON, formula
#line 160 "mona.y"
{ CurrentSemanticValue = MkQ0Formula(ValueStack[ValueStack.Depth-4], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 86: // formula -> Q, univs, vws, COLON, formula
#line 161 "mona.y"
{ CurrentSemanticValue = MkQFormula(ValueStack[ValueStack.Depth-5], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1], ValueStack[ValueStack.Depth-4]); }
        break;
      case 87: // formula -> Q, vws, COLON, formula
#line 162 "mona.y"
{ CurrentSemanticValue = MkQFormula(ValueStack[ValueStack.Depth-4], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1], null); }
        break;
      case 88: // formula -> NAME, LPAR, RPAR
#line 163 "mona.y"
{ CurrentSemanticValue = MkPredApp(ValueStack[ValueStack.Depth-3], MkList<MonaExpr>()); }
        break;
      case 89: // formula -> NAME, LPAR, exprs, RPAR
#line 164 "mona.y"
{ CurrentSemanticValue = MkPredApp(ValueStack[ValueStack.Depth-4], ValueStack[ValueStack.Depth-2]); }
        break;
      case 90: // formula -> formula, AND, formula
#line 165 "mona.y"
{ CurrentSemanticValue = MkBooleanFormula(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 91: // formula -> formula, OR, formula
#line 166 "mona.y"
{ CurrentSemanticValue = MkBooleanFormula(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 92: // formula -> formula, IMPLIES, formula
#line 167 "mona.y"
{ CurrentSemanticValue = MkBooleanFormula(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 93: // formula -> formula, EQUIV, formula
#line 168 "mona.y"
{ CurrentSemanticValue = MkBooleanFormula(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 94: // formula -> term, EQ, term
#line 169 "mona.y"
{ CurrentSemanticValue = MkAtom2(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 95: // formula -> term, NE, term
#line 170 "mona.y"
{ CurrentSemanticValue = MkAtom2(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 96: // formula -> term1, GT, term1
#line 171 "mona.y"
{ CurrentSemanticValue = MkAtom2(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 97: // formula -> term1, GE, term1
#line 172 "mona.y"
{ CurrentSemanticValue = MkAtom2(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 98: // formula -> term1, LT, term1
#line 173 "mona.y"
{ CurrentSemanticValue = MkAtom2(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 99: // formula -> term1, LE, term1
#line 174 "mona.y"
{ CurrentSemanticValue = MkAtom2(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 100: // formula -> term1, IN, term2
#line 175 "mona.y"
{ CurrentSemanticValue = MkAtom2(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 101: // formula -> term1, NOTIN, term2
#line 176 "mona.y"
{ CurrentSemanticValue = MkAtom2(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 102: // formula -> term2, SUBSET, term2
#line 177 "mona.y"
{ CurrentSemanticValue = MkAtom2(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 104: // formula -> NAME
#line 179 "mona.y"
{ CurrentSemanticValue = MkName(ValueStack[ValueStack.Depth-1]); }
        break;
      case 105: // letexpr -> LET0, letexprs0, IN, formula
#line 183 "mona.y"
{ CurrentSemanticValue = MkLet(ValueStack[ValueStack.Depth-4], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 106: // letexpr -> LET1, letexprs1, IN, formula
#line 184 "mona.y"
{ CurrentSemanticValue = MkLet(ValueStack[ValueStack.Depth-4], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 107: // letexpr -> LET2, letexprs2, IN, formula
#line 185 "mona.y"
{ CurrentSemanticValue = MkLet(ValueStack[ValueStack.Depth-4], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 114: // exprs -> expr, COMMA, exprs
#line 197 "mona.y"
{ CurrentSemanticValue = MkList<MonaExpr>(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 115: // exprs -> expr
#line 198 "mona.y"
{ CurrentSemanticValue = MkList<MonaExpr>(ValueStack[ValueStack.Depth-1]); }
        break;
      case 120: // names -> NAME, COMMA, names
#line 212 "mona.y"
{ CurrentSemanticValue = MkList<Token>(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 121: // names -> NAME
#line 213 "mona.y"
{ CurrentSemanticValue = MkList<Token>(ValueStack[ValueStack.Depth-1]); }
        break;
      case 122: // univs -> LBRACKET, NAME, univs_
#line 217 "mona.y"
{ CurrentSemanticValue = MkList<Token>(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-2]); }
        break;
      case 123: // univs_ -> RBRACKET
#line 220 "mona.y"
{ CurrentSemanticValue = MkList<Token>(); }
        break;
      case 124: // univs_ -> COMMA, NAME, univs_
#line 221 "mona.y"
{ CurrentSemanticValue = MkList<Token>(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-1]); }
        break;
      case 125: // term1 -> NUMBER
#line 225 "mona.y"
{ CurrentSemanticValue = MkInt(ValueStack[ValueStack.Depth-1]); }
        break;
      case 126: // term1 -> LPAR, term1, RPAR
#line 226 "mona.y"
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-2]; }
        break;
      case 127: // term1 -> term1, PLUS, term1
#line 227 "mona.y"
{ CurrentSemanticValue = MkArithmFuncApp(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 128: // term1 -> term1, MINUS, term1
#line 228 "mona.y"
{ CurrentSemanticValue = MkArithmFuncApp(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 129: // term1 -> term1, TIMES, term1
#line 229 "mona.y"
{ CurrentSemanticValue = MkArithmFuncApp(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 130: // term1 -> term1, DIV, term1
#line 230 "mona.y"
{ CurrentSemanticValue = MkArithmFuncApp(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 131: // term1 -> term1, MOD, term1
#line 231 "mona.y"
{ CurrentSemanticValue = MkArithmFuncApp(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 132: // term1 -> MIN, term2
#line 232 "mona.y"
{ CurrentSemanticValue = MkMinOrMax(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-1]); }
        break;
      case 133: // term1 -> MAX, term2
#line 233 "mona.y"
{ CurrentSemanticValue = MkMinOrMax(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-1]); }
        break;
      case 134: // term1 -> NAME
#line 234 "mona.y"
{ CurrentSemanticValue = MkName(ValueStack[ValueStack.Depth-1]); }
        break;
      case 135: // term2 -> LPAR, term2, RPAR
#line 238 "mona.y"
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-2]; }
        break;
      case 136: // term2 -> LBRACE, RBRACE
#line 239 "mona.y"
{ CurrentSemanticValue = MkSet(ValueStack[ValueStack.Depth-2], MkList<MonaExpr>()); }
        break;
      case 137: // term2 -> LBRACE, elemslist, RBRACE
#line 240 "mona.y"
{ CurrentSemanticValue = MkSet(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-2]); }
        break;
      case 138: // term2 -> EMPTY
#line 241 "mona.y"
{ CurrentSemanticValue = MkSet(ValueStack[ValueStack.Depth-1]); }
        break;
      case 139: // term2 -> PCONST, LPAR, intterm, RPAR
#line 242 "mona.y"
{ CurrentSemanticValue = MkPconst(ValueStack[ValueStack.Depth-4], ValueStack[ValueStack.Depth-2]); }
        break;
      case 140: // term2 -> term2, UNION, term2
#line 243 "mona.y"
{ CurrentSemanticValue = MkSetOp(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 141: // term2 -> term2, INTER, term2
#line 244 "mona.y"
{ CurrentSemanticValue = MkSetOp(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 142: // term2 -> term2, SETMINUS, term2
#line 245 "mona.y"
{ CurrentSemanticValue = MkSetOp(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 143: // term2 -> term2, PLUS, intterm
#line 246 "mona.y"
{ CurrentSemanticValue = MkSetOp(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 144: // term2 -> term2, MINUS, intterm
#line 247 "mona.y"
{ CurrentSemanticValue = MkSetOp(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 145: // term2 -> NAME
#line 248 "mona.y"
{ CurrentSemanticValue = MkName(ValueStack[ValueStack.Depth-1]); }
        break;
      case 146: // elemslist -> elems, COMMA, elemslist
#line 252 "mona.y"
{ CurrentSemanticValue = MkList<MonaExpr>(ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 147: // elemslist -> elems
#line 253 "mona.y"
{ CurrentSemanticValue = MkList<MonaExpr>(ValueStack[ValueStack.Depth-1]); }
        break;
      case 148: // elems -> term1, RANGE, term1
#line 257 "mona.y"
{ CurrentSemanticValue = MkRange(ValueStack[ValueStack.Depth-2], ValueStack[ValueStack.Depth-3], ValueStack[ValueStack.Depth-1]); }
        break;
      case 150: // letexprs0 -> NAME, EQ, formula0, COMMA, letexprs0
#line 262 "mona.y"
{ CurrentSemanticValue = MkList<Tuple<Token,MonaExpr>>(new Tuple<Token,MonaExpr>((Token)ValueStack[ValueStack.Depth-5],(MonaExpr)ValueStack[ValueStack.Depth-3]), ValueStack[ValueStack.Depth-1]); }
        break;
      case 151: // letexprs0 -> NAME, EQ, formula0
#line 263 "mona.y"
{ CurrentSemanticValue = MkList<Tuple<Token,MonaExpr>>(new Tuple<Token,MonaExpr>((Token)ValueStack[ValueStack.Depth-3],(MonaExpr)ValueStack[ValueStack.Depth-1])); }
        break;
      case 152: // letexprs1 -> NAME, EQ, term1, COMMA, letexprs1
#line 267 "mona.y"
{ CurrentSemanticValue = MkList<Tuple<Token,MonaExpr>>(new Tuple<Token,MonaExpr>((Token)ValueStack[ValueStack.Depth-5],(MonaExpr)ValueStack[ValueStack.Depth-3]), ValueStack[ValueStack.Depth-1]); }
        break;
      case 153: // letexprs1 -> NAME, EQ, term1
#line 268 "mona.y"
{ CurrentSemanticValue = MkList<Tuple<Token,MonaExpr>>(new Tuple<Token,MonaExpr>((Token)ValueStack[ValueStack.Depth-3],(MonaExpr)ValueStack[ValueStack.Depth-1])); }
        break;
      case 154: // letexprs2 -> NAME, EQ, term2, COMMA, letexprs2
#line 272 "mona.y"
{ CurrentSemanticValue = MkList<Tuple<Token,MonaExpr>>(new Tuple<Token,MonaExpr>((Token)ValueStack[ValueStack.Depth-5],(MonaExpr)ValueStack[ValueStack.Depth-3]), ValueStack[ValueStack.Depth-1]); }
        break;
      case 155: // letexprs2 -> NAME, EQ, term2
#line 273 "mona.y"
{ CurrentSemanticValue = MkList<Tuple<Token,MonaExpr>>(new Tuple<Token,MonaExpr>((Token)ValueStack[ValueStack.Depth-3],(MonaExpr)ValueStack[ValueStack.Depth-1])); }
        break;
      case 156: // formula0 -> LPAR, formula, RPAR
#line 277 "mona.y"
{ CurrentSemanticValue = ValueStack[ValueStack.Depth-2]; }
        break;
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliasses != null && aliasses.ContainsKey(terminal))
        return aliasses[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

}
}
